/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AddressBook3;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test 
    public void testRotateLeft() {
        Table table = new Table();
        table.insert("5","5");
        table.insert("6","6");
        table.insert("7","7");
        assertEquals("6", table.getRoot().getKey());
        assertEquals(1,table.getRoot().getHeight());
        assertEquals(0,table.getRoot().getBalance());
        assertEquals("5", table.getRoot().getLeftChild().getKey());
        assertEquals(0,table.getRoot().getLeftChild().getHeight());
        assertEquals(0,table.getRoot().getLeftChild().getBalance());
        assertEquals("7", table.getRoot().getRightChild().getKey());
        assertEquals(0,table.getRoot().getRightChild().getHeight());
        assertEquals(0,table.getRoot().getRightChild().getBalance());
    }

    @Test
    public void testRotateRight() {
        Table table = new Table();
        table.insert("7","7");
        table.insert("6","6");
        table.insert("5","5");      
        assertEquals("6", table.getRoot().getKey());
        assertEquals(1,table.getRoot().getHeight());
        assertEquals(0,table.getRoot().getBalance());
        assertEquals("5", table.getRoot().getLeftChild().getKey());
        assertEquals(0,table.getRoot().getLeftChild().getHeight());
        assertEquals(0,table.getRoot().getLeftChild().getBalance());
        assertEquals("7", table.getRoot().getRightChild().getKey());
        assertEquals(0,table.getRoot().getRightChild().getHeight());
        assertEquals(0,table.getRoot().getRightChild().getBalance());
    }

    @Test
    public void testDeleteandRotate(){
        Table table = new Table();
        table.insert("5","5");
        table.insert("1","1");
        table.insert("9","9"); 
        table.insert("0","0");
        table.insert("2","2"); 

        table.delete("9");
        assertEquals("1", table.getRoot().getKey());

        table.delete("1");
        assertEquals("2", table.getRoot().getKey());
    }
}
